# ssl-acme.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-acme
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: user@email.com
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: user@email.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: apikey
      selector:
        dnsNames:
        - 'mydomain.com'
        - '*.mydomain.com'