# test-certificate.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-mydomain-com
spec:
  secretName: mydomain-com-testtls # <- Secret resource used to store certificate
  issuerRef:
    name: letsencrypt-staging # <- name of the issuer, created before
    kind: ClusterIssuer
  commonName: '*.mydomain.com'
  dnsNames:
  - mydomain.com
  - '*.mydomain.com'